### ISSUE TITLE
Data preparation holes

### ISSUE THREAD

**Issue by kampelmuehler** [chenweikai/3PSDF#2]
Hi,

when I run the data preparation demo with the soldier and octree depth of 7 the mesh that is reconstructed for debugging purposes has strange slits/holes (see screenshot) - is this normal?

![grafik](https://user-images.githubusercontent.com/9306799/185149427-a10ee229-4d03-48ba-9db0-e51a1640a3af.png)

Thanks

**Comment by chenweikai** [comment]
> Hi,
> 
> when I run the data preparation demo with the soldier and octree depth of 7 the mesh that is reconstructed for debugging purposes has strange slits/holes (see screenshot) - is this normal?
> 
> ![grafik](https://user-images.githubusercontent.com/9306799/185149427-a10ee229-4d03-48ba-9db0-e51a1640a3af.png)
> 
> Thanks

Hi,

These slits are introduced as we applied localized Marching cubes to reconstruct the 3PSDF field from octree cells. That means the marching cubes are applied independently inside each octree cell without considering the continuity of its neighboring cells. Hence, since 1) some octree cell is larger or smaller than its neighboring cells, and 2) the marching cubes can only reconstruct limited topologies, there will be gaps between the resulting meshes in adjacent meshes. The reason we have to use localized marching cubes is that the sampling points lie on the octree grid, which is not a regular point grid that can be directly applied using the marching cubes algorithm.

However, as noted in the code, it is only for debugging purposes to visualize the overall shape of your obtained 3PSDF field. It would not affect the network training. So no worries!:-)

**Comment by kampelmuehler** [comment]
Thanks for getting back to me on such short notice and for the very informative reply :)
